repos:
  - repo: local
    hooks:
      - id: go mod tidy
        name: go mod tidy
        language: system
        entry: go mod tidy
        pass_filenames: false
        types: [go]
      - id: go generate
        name: go generate
        language: system
        pass_filenames: false
        entry: go generate -x ./...
        types: [go]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.53.3
    hooks:
      - id: golangci-lint
