// Code generated by ent, DO NOT EDIT.

//go:build tools
// +build tools

// Package internal holds a loadable version of the latest schema.
package internal

const Schema = `{"Schema":"MODULE_NAME/pkg/database/ent/schema","Package":"MODULE_NAME/pkg/database/ent","Schemas":[{"name":"User","config":{"Table":""}}],"Features":["sql/lock","sql/modifier","sql/execquery","sql/upsert","schema/snapshot","privacy","entql"]}`
