// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"MODULE_NAME/app"
	"MODULE_NAME/pkg/config"
	"MODULE_NAME/pkg/crontab"
	"MODULE_NAME/pkg/database"
	"MODULE_NAME/pkg/database/ent"
	"MODULE_NAME/pkg/logger"
	"MODULE_NAME/pkg/redis"
	"MODULE_NAME/pkg/server"
	"github.com/google/wire"
)

// Injectors from wire.go:

func CreateServer() (*server.Server, func(), error) {
	koanf, cleanup, err := config.New()
	if err != nil {
		return nil, nil, err
	}
	options, err := server.NewOptions(koanf)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	mountFunc := app.NewHandler()
	loggerOptions, err := logger.NewOptions(koanf)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	zerologLogger := logger.New(loggerOptions)
	serverServer, err := server.New(options, mountFunc, zerologLogger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return serverServer, func() {
		cleanup()
	}, nil
}

func CreateCrontab() (*crontab.Crontab, func(), error) {
	koanf, cleanup, err := config.New()
	if err != nil {
		return nil, nil, err
	}
	options, err := logger.NewOptions(koanf)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	zerologLogger := logger.New(options)
	redisOptions, err := redis.NewOptions(koanf)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	locker, err := redis.NewLock(redisOptions)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	registerFunc := app.NewCrontab()
	crontabCrontab := crontab.New(zerologLogger, locker, registerFunc)
	return crontabCrontab, func() {
		cleanup()
	}, nil
}

func CreateDatabase() (*ent.Client, func(), error) {
	koanf, cleanup, err := config.New()
	if err != nil {
		return nil, nil, err
	}
	options, err := database.NewOptions(koanf)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	loggerOptions, err := logger.NewOptions(koanf)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	zerologLogger := logger.New(loggerOptions)
	client, err := database.New(options, zerologLogger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return client, func() {
		cleanup()
	}, nil
}

// wire.go:

var providerSet = wire.NewSet(config.ProviderSet, logger.ProviderSet, server.ProviderSet, app.ProviderSet, crontab.ProviderSet, redis.ProviderSet, database.ProviderSet)
